const bach_song = {
  "rate" : 90,
  "note_to_color" : {
    "C": "#eedada",
    "D": "#bdafc3	",
    "E": "#83757e",
    "F": "#939883",
    "G": "#585a47",
    "A": "#a2c8ec",
    "B": "#284b70",
    "C#": "#eedada",
    "D#": "#bdafc3",
    "E#": "#83757e",
    "F#": "#939883",
    "G#": "#585a47",
    "A#": "#a2c8ec",
    "B#": "#284b70"
  },
  "notes" : [
    {"note": "G", "duration": 2, "octave": 2},
    {"note": "D", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "A", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "D", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "D", "duration": 2, "octave": 3},

    {"note": "G", "duration": 2, "octave": 2},
    {"note": "D", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "A", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "D", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "D", "duration": 2, "octave": 3},

    {"note": "G", "duration": 2, "octave": 2},
    {"note": "E", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    {"note": "E", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    {"note": "E", "duration": 2, "octave": 3},

    {"note": "G", "duration": 2, "octave": 2},
    {"note": "E", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    {"note": "E", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    { "note": "E", "duration": 2, "octave": 3 },
    
    {"note": "G", "duration": 2, "octave": 2},
    {"note": "F#", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    {"note": "F#", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    { "note": "F#", "duration": 2, "octave": 3 },
    
    {"note": "G", "duration": 2, "octave": 2},
    {"note": "F#", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    {"note": "F#", "duration": 2, "octave": 3},
    {"note": "C", "duration": 2, "octave": 4},
    { "note": "F#", "duration": 2, "octave": 3 },
    
    {"note": "G", "duration": 2, "octave": 2},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "A", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    { "note": "G", "duration": 2, "octave": 3 },

    {"note": "G", "duration": 2, "octave": 2},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "A", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    { "note": "F#", "duration": 2, "octave": 3 },
    
    {"note": "G", "duration": 2, "octave": 2},
    {"note": "E", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "A", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 3},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "F#", "duration": 2, "octave": 3},
    { "note": "G", "duration": 2, "octave": 3 },
    
    {"note": "E", "duration": 2, "octave": 3},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "F#", "duration": 2, "octave": 3},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "B", "duration": 2, "octave": 2},
    {"note": "D", "duration": 2, "octave": 3},
    {"note": "C#", "duration": 2, "octave": 3},
    { "note": "B", "duration": 2, "octave": 2 },

    {"note": "C#", "duration": 2, "octave": 3},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "A", "duration": 2, "octave": 3},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "A", "duration": 2, "octave": 3},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "A", "duration": 2, "octave": 3},
    { "note": "G", "duration": 2, "octave": 3 },

    {"note": "C#", "duration": 2, "octave": 3},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "A", "duration": 2, "octave": 3},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "A", "duration": 2, "octave": 3},
    {"note": "G", "duration": 2, "octave": 3},
    {"note": "A", "duration": 2, "octave": 3},
    { "note": "G", "duration": 2, "octave": 3 },
  ]
};



// \["([A-G])", (\d)\]